services:
  mailhog:
    image: mailhog/mailhog:latest
    container_name: mailhog
    ports:
      - "8025:8025"
      - "1025:1025"
    networks:
      - insights-network

  insights:
    build: .
    container_name: insights
    depends_on:
      - mailhog
    env_file:
      - subscribe.env
    networks:
      - insights-network
    volumes:
      - ./main/output:/app/main/output

networks:
  insights-network:
    driver: bridge
